version: 0.2

phases:
  install:
    commands:
      - echo Installing Packages and Test Package -Jest *
      - npm install -g
      - npm install jest -g 

  pre_build:
    commands:
      - echo Working on adding steps to pre phase, nginx configurations...

  build:
    commands:
      - echo Build started on `date`
      - npm build 
      - npm test

  post_build:
    commands:
      - echo Build completed on `date`
      - sed -i 's|YOUR_DOMAIN_HERE|https://zapier-qa1.datalogics.com|' config/settings.js
      - npm test 

artifacts:
  files:
    - ./**/*